### PR TITLE
fix: add a queue to throttle requests and avoid 429 errors

### LINKED ISSUE #309: Many new videos trigger a 429 Too Many Requests from Mux
```javascript 

✗ Error creating a Mux Direct Upload

RateLimitError: 429 {"errors":["Too many requests, retry later."]}
    at APIError.generate (file:///home/user/projects/clients/sonnenglas/tailwindui-commit/sonnenglas-changelog/node_modules/@mux/mux-node/error.mjs:54:20)
    at Mux.makeStatusError (file:///home/user/projects/clients/sonnenglas/tailwindui-commit/sonnenglas-changelog/node_modules/@mux/mux-node/core.mjs:246:25)
    at Mux.makeRequest (file:///home/user/projects/clients/sonnenglas/tailwindui-commit/sonnenglas-changelog/node_modules/@mux/mux-node/core.mjs:289:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.uploadLocalFile (file:///home/user/projects/clients/sonnenglas/tailwindui-commit/sonnenglas-changelog/node_modules/next-video/dist/providers/mux/provider.js:113:14) {
  status: 429,
  headers: {
    'cache-control': 'max-age=0, private, must-revalidate',
    'content-length': '46',
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 28 Oct 2024 12:03:26 GMT',
    server: 'Mux API Server',
    'x-request-id': 'GAKcQF6BfLMPsbAPIOqC'
  },
  error: { errors: [ 'Too many requests, retry later.' ] }
}

```

There should potentially be an additional initial request delay introduced.

### PR DESCRIPTION
**Pull request by R-Delfino95**
Closes #309 

- Created a queue that limits the creation of upload URLs to one per second, preventing "Too Many Requests" (429) errors.

### CODE REVIEW

**Review by luwes — CHANGES_REQUESTED** [review]
this looks good! could you put the queue specific code in a utils/queue file?

also I think right now, the first request is also delayed 1s. that shouldn't be the case I think?

File: src/utils/queue.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+export function stopProcessingQueue() {
+  if (intervalId) {
+    clearInterval(intervalId);
+    intervalId = undefined;
+  }
+}
+
+export async function enqueueMethod<T>(fn: () => Promise<T>): Promise<T> {
+    if (firstItemInQueue) {
```
Comment (luwes) [inline src/utils/queue.ts:36]: this needs some more thought because subsequent delayed (> 1s) first enqueue calls will not get in this block while they should.

this variable needs to be reset to true after the last item has left the queue after 1s.

File: src/utils/queue.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
+export interface QueueItem<T = any> {
+    fn: () => Promise<T>;
+    resolve: (value: T) => void;
+    reject: (reason?: any) => void;
+}
+
+let intervalId: NodeJS.Timeout | undefined = undefined;
+let firstItemInQueue: boolean = true;
+const requestQueue: QueueItem[] = [];
```
Comment (luwes) [inline src/utils/queue.ts:9]: just noting here that for our use case this is okay but generally a new queue is created in the module where you need it. if we were to use this in different providers and we supported enabling multiple providers in the same app the requests of different providers would get mixed here.

File: tests/cli/sync.test.ts [hunk 3]
```diff
@@ -10,6 +10,7 @@ import log from '../../src/utils/logger.js';
 
 import { handler, builder } from '../../src/cli/sync.js';
 import { createAsset, updateAsset } from '../../src/assets.js';
+import { queue } from '../../src/providers/mux/provider.js';
```
Comment (luwes) [inline tests/cli/sync.test.ts:13]: is it possible to not have to import this here and call `stopProcessingQueue`? 

I think maybe better than using an interval is to use a last requested timestamp and a set a timeout if needed.
that way every time the last request is made, the timers are cleaned up...

Comment (R-Delfino95) [reply tests/cli/sync.test.ts]: Yes! I updated the implementation to use `setTimeout` instead of `setInterval`.
Now the queue is more encapsulated, there's no need to export it or use the `stopProcessingQueue`.
